apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-0loc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-0loc
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-0loc
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-0loc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-0loc
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-yruk-tenant/rhtap-demo-app/hacbs-test-project-0loc@sha256:00553df700977179155edf89c19dbbfb38f16eac745ddd2cf38196f61c2c70d3
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
